# Generated by Django 5.2.16 on 2026-07-13 22:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decisions', '0001_initial'),
        ('organisations', '0002_membership_uniq_active_membership_per_user'),
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('work_type', models.CharField(choices=[('action', 'Acção'), ('review', 'Revisão'), ('validation', 'Validação'), ('obligation', 'Obrigação'), ('decision_follow_up', 'Seguimento de decisão')], max_length=32, verbose_name='tipo')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='medium', max_length=16, verbose_name='prioridade')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='prazo')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='open', max_length=16, verbose_name='estado')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelada em')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='versão')),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_items', to='decisions.decision', verbose_name='decisão')),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organisations.organisation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_items', to='portfolio.product', verbose_name='produto')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_work_items', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'pendência',
                'verbose_name_plural': 'pendências',
                'db_table': 'work_items_workitem',
                'ordering': ['-created_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='work_items_workitem_title_not_blank'), models.CheckConstraint(condition=models.Q(('work_type__in', ('action', 'review', 'validation', 'obligation', 'decision_follow_up'))), name='work_items_workitem_type_closed'), models.CheckConstraint(condition=models.Q(('priority__in', ('low', 'medium', 'high'))), name='work_items_workitem_priority_closed'), models.CheckConstraint(condition=models.Q(('status__in', ('open', 'completed', 'cancelled'))), name='work_items_workitem_status_closed'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='work_items_workitem_version_positive')],
            },
        ),
    ]
