# Generated by Django 5.2.16 on 2026-07-14 00:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('organisations', '0002_membership_uniq_active_membership_per_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('actor_type', models.CharField(choices=[('human', 'Humana'), ('ai', 'IA'), ('hybrid', 'Híbrida')], max_length=16, verbose_name='tipo de actor')),
                ('purpose', models.TextField(verbose_name='propósito')),
                ('responsibilities', models.TextField(verbose_name='responsabilidades')),
                ('constraints', models.TextField(blank=True, verbose_name='limites')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='requer aprovação')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva')], default='active', max_length=16, verbose_name='estado')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='versão')),
                ('instruction_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instruction_functions', to='documents.document', verbose_name='documento de instruções')),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'função organizacional',
                'verbose_name_plural': 'funções organizacionais',
                'db_table': 'functions_functionprofile',
                'ordering': ['-created_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='functions_functionprofile_name_not_blank'), models.CheckConstraint(condition=models.Q(('purpose', ''), _negated=True), name='functions_functionprofile_purpose_not_blank'), models.CheckConstraint(condition=models.Q(('responsibilities', ''), _negated=True), name='functions_functionprofile_responsibilities_not_blank'), models.CheckConstraint(condition=models.Q(('actor_type__in', ('human', 'ai', 'hybrid'))), name='functions_functionprofile_actor_type_closed'), models.CheckConstraint(condition=models.Q(('status__in', ('active', 'inactive'))), name='functions_functionprofile_status_closed'), models.CheckConstraint(condition=models.Q(models.Q(('actor_type__in', ('ai', 'hybrid')), _negated=True), ('requires_approval', True), _connector='OR'), name='functions_functionprofile_ai_requires_approval'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='functions_functionprofile_version_positive')],
            },
        ),
    ]
