# Generated by Django 5.2.16 on 2026-07-13 22:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('organisations', '0002_membership_uniq_active_membership_per_user'),
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('context', models.TextField(verbose_name='contexto')),
                ('decision_text', models.TextField(verbose_name='decisão')),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data da decisão')),
                ('impact', models.TextField(blank=True, verbose_name='impacto')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('superseded', 'Substituída')], default='active', max_length=16, verbose_name='estado')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='versão')),
                ('detail_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detailed_decisions', to='documents.document', verbose_name='documento de detalhe')),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organisations.organisation')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='portfolio.product', verbose_name='produto')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_decisions', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('supersedes', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced_by', to='decisions.decision', verbose_name='substitui')),
            ],
            options={
                'verbose_name': 'decisão',
                'verbose_name_plural': 'decisões',
                'db_table': 'decisions_decision',
                'ordering': ['-decided_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='decisions_decision_title_not_blank'), models.CheckConstraint(condition=models.Q(('context', ''), _negated=True), name='decisions_decision_context_not_blank'), models.CheckConstraint(condition=models.Q(('decision_text', ''), _negated=True), name='decisions_decision_text_not_blank'), models.CheckConstraint(condition=models.Q(('status__in', ('active', 'superseded'))), name='decisions_decision_status_closed'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='decisions_decision_version_positive')],
            },
        ),
    ]
