# Generated by Django 5.2.16 on 2026-07-13 11:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0002_membership_uniq_active_membership_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('purpose', models.TextField(verbose_name='propósito')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('archived', 'Arquivado')], default='active', max_length=16, verbose_name='estado')),
                ('last_reviewed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='última revisão')),
                ('target_audience', models.CharField(blank=True, max_length=255, verbose_name='público-alvo')),
                ('phase', models.CharField(blank=True, max_length=64, verbose_name='fase')),
                ('next_review_at', models.DateTimeField(blank=True, null=True, verbose_name='próxima revisão')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='versão')),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organisations.organisation')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_products', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'db_table': 'portfolio_product',
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='portfolio_product_name_not_blank'), models.CheckConstraint(condition=models.Q(('purpose', ''), _negated=True), name='portfolio_product_purpose_not_blank'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='portfolio_product_version_positive')],
            },
        ),
    ]
