# Generated by Django 5.2.16 on 2026-07-12 22:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('auth.login', 'Login'), ('auth.logout', 'Logout'), ('auth.failed', 'Falha de autenticação'), ('organisation.created', 'Empresa criada'), ('organisation.updated', 'Empresa alterada'), ('product.created', 'Produto criado'), ('product.updated', 'Produto alterado'), ('product.archived', 'Produto arquivado'), ('document.created', 'Documento criado'), ('document.updated', 'Documento alterado'), ('document.version_created', 'Versão criada'), ('document.version_restored', 'Versão restaurada'), ('decision.created', 'Decisão criada'), ('decision.updated', 'Decisão alterada'), ('work_item.created', 'Pendência criada'), ('work_item.updated', 'Pendência alterada'), ('function.created', 'Função criada'), ('function.updated', 'Função alterada'), ('execution.created', 'Execução criada'), ('context_package.exported', 'Pacote exportado'), ('result.imported', 'Resultado importado'), ('result.approved', 'Resultado aprovado'), ('result.rejected', 'Resultado rejeitado'), ('result.correction_requested', 'Correcção pedida'), ('change.applied', 'Alteração aplicada'), ('data.exported', 'Dados exportados'), ('membership.changed', 'Membros/papéis alterados'), ('security.cross_org_attempt', 'Acesso cruzado'), ('storage.failure', 'Falha de armazenamento')], max_length=48)),
                ('result', models.CharField(choices=[('success', 'Sucesso'), ('failure', 'Falha'), ('denied', 'Recusado')], default='success', max_length=16)),
                ('actor_id_snapshot', models.CharField(blank=True, max_length=64)),
                ('organisation_id_snapshot', models.CharField(blank=True, max_length=64)),
                ('entity_type', models.CharField(blank=True, max_length=64)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'evento de auditoria',
                'verbose_name_plural': 'eventos de auditoria',
                'db_table': 'audit_auditevent',
                'ordering': ['-created_at'],
            },
        ),
    ]
