# Generated by Django 5.2.16 on 2026-07-13 10:36

import django.db.models.functions.text
from django.db import migrations, models


def normalize_existing_emails(apps, schema_editor):
    """Normaliza (strip+lower) os emails existentes e detecta colisões CI.

    Não funde nem apaga contas: se dois registos colidirem por capitalização,
    falha com mensagem clara para resolução manual.
    """
    CustomUser = apps.get_model("accounts", "CustomUser")
    seen = {}
    for user in CustomUser.objects.all().order_by("created_at"):
        canonical = (user.email or "").strip().lower()
        if canonical in seen:
            raise RuntimeError(
                "Colisão de email case-insensitive detectada: "
                f"{canonical!r} (contas {seen[canonical]} e {user.pk}). "
                "Resolva manualmente antes de migrar; nenhuma conta foi "
                "fundida nem apagada."
            )
        seen[canonical] = str(user.pk)
        if user.email != canonical:
            user.email = canonical
            user.save(update_fields=["email"])


def noop_reverse(apps, schema_editor):
    # A normalização é irreversível de forma segura; nada a desfazer.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresettoken_ratelimitattempt'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ratelimitattempt',
            index=models.Index(fields=['created_at'], name='accounts_ra_created_47fe39_idx'),
        ),
        # Normaliza dados existentes e verifica colisões antes de impor a constraint.
        migrations.RunPython(normalize_existing_emails, noop_reverse),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='uniq_customuser_email_ci'),
        ),
    ]
