# Generated by Django 5.2.16 on 2026-07-14 03:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('functions', '0001_initial'),
        ('organisations', '0002_membership_uniq_active_membership_per_user'),
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('objective', models.TextField(verbose_name='objectivo')),
                ('request_instructions', models.TextField(verbose_name='instruções do pedido')),
                ('constraints', models.TextField(blank=True, verbose_name='restrições')),
                ('expected_output_format', models.TextField(verbose_name='formato esperado')),
                ('execution_mode', models.CharField(choices=[('manual_local', 'Manual local'), ('manual_external', 'Manual externa')], max_length=20, verbose_name='modo de execução')),
                ('status', models.CharField(choices=[('prepared', 'Preparada'), ('result_pending_validation', 'Resultado por validar'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('completed', 'Concluída')], default='prepared', editable=False, max_length=32, verbose_name='estado')),
                ('function_snapshot', models.JSONField(default=dict, editable=False, verbose_name='snapshot da função')),
                ('product_snapshot', models.JSONField(default=dict, editable=False, verbose_name='snapshot do produto')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='versão')),
                ('function_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='functions.functionprofile', verbose_name='função')),
                ('instruction_version', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instruction_executions', to='documents.documentversion', verbose_name='versão de instruções')),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organisations.organisation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='portfolio.product', verbose_name='produto')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_executions', to=settings.AUTH_USER_MODEL, verbose_name='solicitada por')),
            ],
            options={
                'verbose_name': 'execução assistida',
                'verbose_name_plural': 'execuções assistidas',
                'db_table': 'executions_aiexecution',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionContextDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(verbose_name='ordem')),
                ('purpose', models.CharField(blank=True, max_length=255, verbose_name='papel no contexto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_version', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='execution_contexts', to='documents.documentversion', verbose_name='versão de documento')),
                ('execution', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='context_documents', to='executions.aiexecution', verbose_name='execução')),
            ],
            options={
                'verbose_name': 'documento de contexto',
                'verbose_name_plural': 'documentos de contexto',
                'db_table': 'executions_executioncontextdocument',
                'ordering': ['execution_id', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='aiexecution',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='executions_aiexecution_title_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='aiexecution',
            constraint=models.CheckConstraint(condition=models.Q(('objective', ''), _negated=True), name='executions_aiexecution_objective_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='aiexecution',
            constraint=models.CheckConstraint(condition=models.Q(('request_instructions', ''), _negated=True), name='executions_aiexecution_request_instructions_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='aiexecution',
            constraint=models.CheckConstraint(condition=models.Q(('expected_output_format', ''), _negated=True), name='executions_aiexecution_output_format_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='aiexecution',
            constraint=models.CheckConstraint(condition=models.Q(('execution_mode__in', ('manual_local', 'manual_external'))), name='executions_aiexecution_mode_closed'),
        ),
        migrations.AddConstraint(
            model_name='aiexecution',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('prepared', 'result_pending_validation', 'approved', 'rejected', 'completed'))), name='executions_aiexecution_status_closed'),
        ),
        migrations.AddConstraint(
            model_name='aiexecution',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='executions_aiexecution_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='executioncontextdocument',
            constraint=models.UniqueConstraint(fields=('execution', 'order'), name='uniq_executioncontext_execution_order'),
        ),
        migrations.AddConstraint(
            model_name='executioncontextdocument',
            constraint=models.UniqueConstraint(fields=('execution', 'document_version'), name='uniq_executioncontext_execution_version'),
        ),
        migrations.AddConstraint(
            model_name='executioncontextdocument',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 1)), name='executions_executioncontext_order_positive'),
        ),
    ]
