# Generated by Django 5.2.16 on 2026-07-14 11:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0002_resultattempt_aiexecution_current_result_attempt_and_more'),
        ('organisations', '0002_membership_uniq_active_membership_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('correction_requested', 'Correcção pedida')], editable=False, max_length=24, verbose_name='decisão')),
                ('observations', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='result_reviews', to='executions.aiexecution', verbose_name='execução')),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='result_reviews', to='organisations.organisation', verbose_name='empresa')),
                ('result_attempt', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='executions.resultattempt', verbose_name='tentativa revista')),
                ('reviewer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='result_reviews', to=settings.AUTH_USER_MODEL, verbose_name='revisor')),
            ],
            options={
                'verbose_name': 'revisão de resultado',
                'verbose_name_plural': 'revisões de resultado',
                'db_table': 'executions_resultreview',
                'ordering': ['execution_id', 'created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('result_attempt',), name='uniq_resultreview_result_attempt'), models.CheckConstraint(condition=models.Q(('decision__in', ('approved', 'rejected', 'correction_requested'))), name='executions_resultreview_decision_closed'), models.CheckConstraint(condition=models.Q(('decision', 'approved'), models.Q(('observations', ''), _negated=True), _connector='OR'), name='executions_resultreview_observations_required')],
            },
        ),
    ]
