# Generated by Django 5.2.16 on 2026-07-14 15:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0001_initial'),
        ('documents', '0001_initial'),
        ('executions', '0003_resultreview'),
        ('organisations', '0002_membership_uniq_active_membership_per_user'),
        ('work_items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_type', models.CharField(choices=[('document', 'Nova versão documental'), ('decision', 'Substituição de decisão'), ('work_item', 'Conclusão de pendência'), ('no_change', 'Fecho sem alteração')], editable=False, max_length=16, verbose_name='tipo de aplicação')),
                ('request_fingerprint', models.CharField(editable=False, max_length=64, verbose_name='impressão do pedido')),
                ('change_summary', models.CharField(blank=True, max_length=255, verbose_name='resumo da alteração')),
                ('rationale', models.CharField(blank=True, max_length=500, verbose_name='justificação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_results', to=settings.AUTH_USER_MODEL, verbose_name='aplicado por')),
                ('base_document_version', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications_as_base', to='documents.documentversion', verbose_name='versão base')),
                ('created_decision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications_as_created', to='decisions.decision', verbose_name='decisão criada')),
                ('created_document_version', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications_as_created', to='documents.documentversion', verbose_name='versão criada')),
                ('execution', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='application', to='executions.aiexecution', verbose_name='execução')),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='result_applications', to='organisations.organisation', verbose_name='empresa')),
                ('result_attempt', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='executions.resultattempt', verbose_name='tentativa aplicada')),
                ('review', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='executions.resultreview', verbose_name='revisão aprovada')),
                ('target_decision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications_as_target', to='decisions.decision', verbose_name='decisão alvo')),
                ('target_document', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='result_applications', to='documents.document', verbose_name='documento alvo')),
                ('target_work_item', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications_as_target', to='work_items.workitem', verbose_name='pendência alvo')),
            ],
            options={
                'verbose_name': 'aplicação de resultado',
                'verbose_name_plural': 'aplicações de resultado',
                'db_table': 'executions_resultapplication',
                'ordering': ['-created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('execution',), name='uniq_resultapplication_execution'), models.CheckConstraint(condition=models.Q(('application_type__in', ('document', 'decision', 'work_item', 'no_change'))), name='executions_resultapplication_type_closed'), models.CheckConstraint(condition=models.Q(models.Q(('application_type', 'document'), _negated=True), models.Q(('target_document__isnull', False), ('base_document_version__isnull', False), ('created_document_version__isnull', False), models.Q(('change_summary', ''), _negated=True)), _connector='OR'), name='executions_resultapplication_document_coherent')],
            },
        ),
    ]
