# Generated by Django 5.2.16 on 2026-07-14 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0001_initial'),
        ('documents', '0001_initial'),
        ('executions', '0004_resultapplication'),
        ('organisations', '0002_membership_uniq_active_membership_per_user'),
        ('work_items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='resultapplication',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('application_type', 'decision'), _negated=True), models.Q(('target_decision__isnull', False), ('created_decision__isnull', False)), _connector='OR'), name='executions_resultapplication_decision_coherent'),
        ),
        migrations.AddConstraint(
            model_name='resultapplication',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('application_type', 'work_item'), _negated=True), ('target_work_item__isnull', False), _connector='OR'), name='executions_resultapplication_work_item_coherent'),
        ),
        migrations.AddConstraint(
            model_name='resultapplication',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('application_type', 'no_change'), _negated=True), models.Q(('rationale', ''), _negated=True), _connector='OR'), name='executions_resultapplication_no_change_coherent'),
        ),
    ]
