# Generated by Django 5.2.16 on 2026-07-13 13:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0002_membership_uniq_active_membership_per_user'),
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('document_type', models.CharField(choices=[('contexto_da_empresa', 'Contexto da empresa'), ('visao_de_produto', 'Visão de produto'), ('instrucoes', 'Instruções'), ('decisao_detalhada', 'Decisão detalhada'), ('resultado', 'Resultado')], max_length=32, verbose_name='tipo')),
                ('is_outdated', models.BooleanField(default=False, verbose_name='desactualizado')),
                ('export_policy', models.CharField(choices=[('allowed', 'Permitida'), ('confirm', 'Com confirmação'), ('denied', 'Recusada')], default='confirm', max_length=16, verbose_name='política de exportação')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='versão de concorrência')),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organisations.organisation')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='portfolio.product', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'db_table': 'documents_document',
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(verbose_name='número de versão')),
                ('storage_key', models.CharField(editable=False, max_length=64, verbose_name='chave de armazenamento')),
                ('checksum', models.CharField(editable=False, max_length=64, verbose_name='checksum SHA-256')),
                ('byte_size', models.PositiveBigIntegerField(editable=False, verbose_name='tamanho em bytes')),
                ('change_summary', models.CharField(blank=True, max_length=255, verbose_name='resumo da alteração')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_versions', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('document', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='documents.document', verbose_name='documento')),
            ],
            options={
                'verbose_name': 'versão de documento',
                'verbose_name_plural': 'versões de documento',
                'db_table': 'documents_documentversion',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='current_version',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.documentversion', verbose_name='versão actual'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='uniq_documentversion_document_number'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gte', 1)), name='documents_documentversion_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.CheckConstraint(condition=models.Q(('storage_key', ''), _negated=True), name='documents_documentversion_storage_key_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.CheckConstraint(condition=models.Q(('checksum', ''), _negated=True), name='documents_documentversion_checksum_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='documents_document_title_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('document_type__in', ['contexto_da_empresa', 'visao_de_produto', 'instrucoes', 'decisao_detalhada', 'resultado'])), name='documents_document_type_closed'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('export_policy__in', ['allowed', 'confirm', 'denied'])), name='documents_document_export_policy_closed'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='documents_document_version_positive'),
        ),
    ]
